#ifndef XERRNO_H
#define XERRNO_H

// 定义网络错误枚举
enum NetworkError {
    XNET_SUCCESS = 0,
    XNET_CORO_EXCEPT,
    XNET_CORO_FAILED,
    XNET_CORO_TIMEOUT,
    XNET_PROTO_UNKNOWN,
    XNET_MEM_FAIL,
    XNET_NOT_IN_COROUTINE,
    XNET_BUFF_LIMIT,
    XNET_TIMEOUT,
    XNET_INVALID_RESPONSE,
    XNET_SERVER_ERROR,
    XNET_CLIENT_ERROR,
    XNET_UNKNOWN_ERROR
};

#endif
